// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEivkJl6se03swhzA9BlY7zE4embXiSqI',
    appId: '1:397870295550:web:5c845f83b04c79ffd6b8af',
    messagingSenderId: '397870295550',
    projectId: 'logim-auth-7c0b4',
    authDomain: 'logim-auth-7c0b4.firebaseapp.com',
    storageBucket: 'logim-auth-7c0b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2gcG2igH4Bmr2NXVp9PLBO5NjP73yhWI',
    appId: '1:397870295550:android:4cdd2b84f2387b3dd6b8af',
    messagingSenderId: '397870295550',
    projectId: 'logim-auth-7c0b4',
    storageBucket: 'logim-auth-7c0b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLl-Jf32x9sZNIiPI65NWoZdlrC35QMU',
    appId: '1:397870295550:ios:b86c47e86deed517d6b8af',
    messagingSenderId: '397870295550',
    projectId: 'logim-auth-7c0b4',
    storageBucket: 'logim-auth-7c0b4.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPLl-Jf32x9sZNIiPI65NWoZdlrC35QMU',
    appId: '1:397870295550:ios:b86c47e86deed517d6b8af',
    messagingSenderId: '397870295550',
    projectId: 'logim-auth-7c0b4',
    storageBucket: 'logim-auth-7c0b4.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEivkJl6se03swhzA9BlY7zE4embXiSqI',
    appId: '1:397870295550:web:429507273a37bb58d6b8af',
    messagingSenderId: '397870295550',
    projectId: 'logim-auth-7c0b4',
    authDomain: 'logim-auth-7c0b4.firebaseapp.com',
    storageBucket: 'logim-auth-7c0b4.appspot.com',
  );
}
